Models/ErrorViewModel.cs
using System;

namespace Times.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Times.Data;
using System;
using System.Linq;

namespace Times.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using(var context = new TimesContext(
                serviceProvider.GetRequiredService<
                DbContextOptions<TimesContext>>()))
                {
                    if(context.Time.Any())
                    {
                        return;
                    }
                    context.Time.AddRange(
                        

                    );
                    context.SaveChanges();
                }
        }
    }
}

Models/Time.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace Times.Models{
    public class Time
    {
        public int Id {get; set;}
        public string Nome {get; set;}
        public string CPF {get; set;}
        public string Descricao {get; set;}
        
        public float Valor {get; set;}
        
        
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Times.Models;

namespace Times.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TimesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Times.Data;
using Times.Models;

namespace Times.Controllers
{
    public class TimesController : Controller
    {
        private readonly TimesContext _context;

        public TimesController(TimesContext context)
        {
            _context = context;
        }

        // GET: Times
        public async Task<IActionResult> Index()
        {
            return View(await _context.Time.ToListAsync());
        }

        // GET: Times/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var time = await _context.Time.FindAsync(id);
            if (time == null)
            {
                return NotFound();
            }
            return View(time);
        }

        // GET: Times/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Times/Create
        // Adicionando os campos preenchidos no banco
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,CPF,Descricao,Valor")] Time time)
        {
            
            
            if (ModelState.IsValid)
            {
                _context.Add(time);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(time);
        }

        // GET: Times/Edit/5
        // Editando os dados via tela
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var time = await _context.Time.FindAsync(id);
            if (time == null)
            {
                return NotFound();
            }
            return View(time);
        }

        // POST: Times/Edit/5
        // Editando os dados via tela
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,CPF,Descricao,Valor")] Time time)
        {
            if (id != time.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(time);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimeExists(time.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(time);
        }

        // GET: Times/Delete/5
        // Excluindo os dados
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var time = await _context.Time
                .FirstOrDefaultAsync(m => m.Id == id);
            if (time == null)
            {
                return NotFound();
            }

            return View(time);
        }

        // POST: Times/Delete/5
        // Apagando os dados do banco
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var time = await _context.Time.FindAsync(id);
            _context.Time.Remove(time);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TimeExists(int id)
        {
            return _context.Time.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vendinha</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Times" asp-action="Index">Vendinha</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Times - <a asp-area="" asp-controller="Times" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Times/Create.cshtml
@model Times.Models.Time

@{
    ViewData["Title"] = "Cadastrar";
}

<header class="p-4 pb-4 mb-4 border-bottom">
        <a href="/frontend/index.html" class="d-flex align-items-center text-dark text-decoration-none">
            <img src="http://www.interfocus.com.br/Content/images/logo_interfocus_default_bottom.png" alt="logo" width="165">
 
            <span class="fs-4">&nbsp Vendinha Interfocus</span>
        </a>
</header>

<h1>Tela de cadastro</h1>

<h4>Cadastrar nova dívida</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                @*  Nome  *@
                <label asp-for="Nome" class="control-label">Nome Completo</label>
                <input asp-for="Nome" class="form-control" maxlength="60" placeholder="Diego Fernando de Souza" required />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*  CPF  *@
                <label asp-for="CPF" class="control-label">CPF</label>
                <input asp-for="CPF" class="form-control" onkeypress="$(this).mask('000.000.000-00');" maxlength="11" placeholder="123.456.789-10" required />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            

            <div class="form-group p-2 mb-1">
                     @*  Descrição  *@
                    <div class="row">
                        <div class="col-md-8">
                            <label asp-for="Descricao" class="control-label">Descricao</label>
                            <input asp-for="Descricao" class="form-control" maxlength="120" placeholder="Digite aqui o que foi comprado"/>
                        </div>                        
                        <div class="col-md-4">
                            @*  Valor  *@
                            <label for="dividaValorInput">Valor Devido</label>
                            <input asp-for="Valor" type="number"class="form-control" placeholder="R$ 0.00" min=".01" step=".01" required>
                        </div>    
                    </div>    
                </div>

            <div class="form-group">
                @*  Button  *@
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info">Voltar para a listagem</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
}

Views/Times/Delete.cshtml
@model Times.Models.Time

@{
    ViewData["Title"] = "Quitar";
}

<header class="p-4 pb-4 mb-4 border-bottom">
        <a href="/frontend/index.html" class="d-flex align-items-center text-dark text-decoration-none">
            <img src="http://www.interfocus.com.br/Content/images/logo_interfocus_default_bottom.png" alt="logo" width="165">
 
            <span class="fs-4">&nbsp Vendinha Interfocus</span>
        </a>
</header>

<h1>Quitar Dívida</h1>

<h3>Você tem certeza que deseja quitar a dívida deste cliente?</h3>
<div>
    <br>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Quitar" class="btn btn-danger" /> 
            <br>
            <br>
        <a asp-action="Index" class="btn btn-info">Voltar para a listagem</a>
    </form>
</div>

Views/Times/Details.cshtml
@model Times.Models.Time

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Dívida</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Valor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Valor)
    </dl>
    
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Editar</a> 
    <br>
    <br>
    <a asp-action="Index" class="btn btn-info">Voltar para a lista</a>
</div>

Views/Times/Edit.cshtml
@model Times.Models.Time

@{
    ViewData["Title"] = "Edit";
}

<header class="p-4 pb-4 mb-4 border-bottom">
        <a href="/frontend/index.html" class="d-flex align-items-center text-dark text-decoration-none">
            <img src="http://www.interfocus.com.br/Content/images/logo_interfocus_default_bottom.png" alt="logo" width="165">
 
            <span class="fs-4">&nbsp Vendinha Interfocus</span>
        </a>
</header>

<h1>Editar</h1>

<h4>Dívida</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome Completo</label>
                <input asp-for="Nome" class="form-control" maxlength="60" placeholder="Diego Fernando de Souza" required />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CPF" class="control-label">CPF</label>
                <input asp-for="CPF" class="form-control" onkeypress="$(this).mask('000.000.000-00');" maxlength="11" placeholder="123.456.789-10" required />
                <span asp-validation-for="CPF" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label">Descricao</label>
                <input asp-for="Descricao" class="form-control" maxlength="120" placeholder="Digite aqui o que foi comprado" />
            </div> 
            <div class="form-group">
                <label for="dividaValorInput">Valor Devido</label>
                <input asp-for="Valor" type="number"class="form-control" placeholder="R$ 0.00" min=".01" step=".01" required>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info">Voltar para a listagem</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
}

Views/Times/Index.cshtml
@model IEnumerable<Times.Models.Time>

@{
    ViewData["Title"] = "Index";
}

<header class="p-4 pb-4 mb-4 border-bottom">
        <a href="/frontend/index.html" class="d-flex align-items-center text-dark text-decoration-none">
            <img src="http://www.interfocus.com.br/Content/images/logo_interfocus_default_bottom.png" alt="logo" width="165">
 
            <span class="fs-4">&nbsp Vendinha Interfocus</span>
        </a>
</header>

<p>
    <a asp-action="Create" class="btn btn-primary">Adicionar nova dívida</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valor)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Quitar</a>
            </td>
        </tr>
}
    </tbody>
</table>